
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package valiente.orl2.phyton.parser;

/** CUP generated class containing symbol constants. */
public class PhytonSym {
  /* terminals */
  public static final int GREATER_THAN = 50;
  public static final int INCREASE = 56;
  public static final int SIR = 87;
  public static final int MI = 42;
  public static final int MENSAJE = 16;
  public static final int CLOSE_BRACKET = 65;
  public static final int SI = 46;
  public static final int CLOSE_CURLY = 79;
  public static final int SPACE = 77;
  public static final int SOL = 44;
  public static final int KEEP = 18;
  public static final int POW = 63;
  public static final int PRIMOS = 13;
  public static final int PISTA = 4;
  public static final int LONGITUD = 15;
  public static final int FALSE = 82;
  public static final int NOT = 75;
  public static final int NOR = 72;
  public static final int FA = 43;
  public static final int ORDENAR = 8;
  public static final int MIR = 83;
  public static final int NULL_ = 52;
  public static final int VAR = 19;
  public static final int LA = 45;
  public static final int RE = 41;
  public static final int EQUAL_MORE = 55;
  public static final int IMPARES = 12;
  public static final int OPEN_BRACKET = 64;
  public static final int DECREASE = 57;
  public static final int HACER = 36;
  public static final int PARES = 11;
  public static final int MULTIPLY = 60;
  public static final int NUMBER = 3;
  public static final int COMA = 69;
  public static final int ENTERO = 20;
  public static final int TRUE = 81;
  public static final int TAB = 76;
  public static final int DOBLE = 21;
  public static final int WHILE = 35;
  public static final int EQUAL = 47;
  public static final int MODULE = 62;
  public static final int DECIMAL = 2;
  public static final int CHAR = 28;
  public static final int BOOLEAN = 22;
  public static final int SWITCH = 30;
  public static final int DO = 40;
  public static final int FOR = 34;
  public static final int SIMBOLO = 26;
  public static final int GREATER = 53;
  public static final int ADD = 58;
  public static final int DIV = 61;
  public static final int ELSE = 29;
  public static final int DOR = 38;
  public static final int LAR = 86;
  public static final int ARREGLO = 25;
  public static final int OPEN_PARENTHESIS = 66;
  public static final int EOF = 0;
  public static final int OPEN_CURLY = 78;
  public static final int DEFAULT = 33;
  public static final int LESSER_THAN = 51;
  public static final int SUMARIZAR = 14;
  public static final int CARACTER = 23;
  public static final int MINUS = 59;
  public static final int DIFFERENTIATION = 49;
  public static final int PRINCIPAL = 17;
  public static final int OR = 73;
  public static final int error = 1;
  public static final int REPRODUCIR = 6;
  public static final int EXIT = 32;
  public static final int LESSER = 54;
  public static final int CONTINUE = 37;
  public static final int RER = 39;
  public static final int EXTIENDE = 5;
  public static final int FAR = 84;
  public static final int COLON = 68;
  public static final int ESPERAR = 7;
  public static final int RETORNA = 80;
  public static final int EQUALIZATION = 48;
  public static final int CASE = 31;
  public static final int CADENA = 24;
  public static final int STRING = 27;
  public static final int ASCENDENTE = 9;
  public static final int SOLR = 85;
  public static final int AND = 71;
  public static final int DESCENDENTE = 10;
  public static final int CLOSE_PARENTHESIS = 67;
  public static final int XOR = 74;
  public static final int NAND = 70;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECIMAL",
  "NUMBER",
  "PISTA",
  "EXTIENDE",
  "REPRODUCIR",
  "ESPERAR",
  "ORDENAR",
  "ASCENDENTE",
  "DESCENDENTE",
  "PARES",
  "IMPARES",
  "PRIMOS",
  "SUMARIZAR",
  "LONGITUD",
  "MENSAJE",
  "PRINCIPAL",
  "KEEP",
  "VAR",
  "ENTERO",
  "DOBLE",
  "BOOLEAN",
  "CARACTER",
  "CADENA",
  "ARREGLO",
  "SIMBOLO",
  "STRING",
  "CHAR",
  "ELSE",
  "SWITCH",
  "CASE",
  "EXIT",
  "DEFAULT",
  "FOR",
  "WHILE",
  "HACER",
  "CONTINUE",
  "DOR",
  "RER",
  "DO",
  "RE",
  "MI",
  "FA",
  "SOL",
  "LA",
  "SI",
  "EQUAL",
  "EQUALIZATION",
  "DIFFERENTIATION",
  "GREATER_THAN",
  "LESSER_THAN",
  "NULL_",
  "GREATER",
  "LESSER",
  "EQUAL_MORE",
  "INCREASE",
  "DECREASE",
  "ADD",
  "MINUS",
  "MULTIPLY",
  "DIV",
  "MODULE",
  "POW",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "COLON",
  "COMA",
  "NAND",
  "AND",
  "NOR",
  "OR",
  "XOR",
  "NOT",
  "TAB",
  "SPACE",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "RETORNA",
  "TRUE",
  "FALSE",
  "MIR",
  "FAR",
  "SOLR",
  "LAR",
  "SIR"
  };
}

