// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: PhytonLexic.flex

package valiente.orl2.phyton.parser;
import com.sun.org.apache.xalan.internal.xsltc.compiler.sym;
import java_cup.runtime.*;
import static valiente.orl2.phyton.parser.PhytonSym.*;
import valiente.orl2.phyton.error.LexicalError;
import java.util.ArrayList;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class PhytonLexic implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\1\2\1\3\1\0\2\1\22\0\1\1"+
    "\1\4\1\5\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\11\23\1\0\1\24\1\25\1\26\1\27\2\0\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\36\1\41\1\42\1\43\1\36\1\44\1\45\1\36"+
    "\1\46\1\47\1\50\1\36\1\51\4\36\1\52\1\0"+
    "\1\53\1\54\1\55\1\0\1\56\1\57\1\60\1\61"+
    "\1\62\1\63\1\64\1\65\1\66\1\67\1\41\1\70"+
    "\1\71\1\72\1\73\1\74\1\36\1\75\1\76\1\77"+
    "\1\100\1\51\1\101\1\102\1\36\1\103\1\104\1\105"+
    "\1\106\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\1\13\1\14\1\1"+
    "\1\15\2\16\1\17\1\20\1\21\1\22\22\23\1\24"+
    "\1\25\1\26\1\27\1\1\1\30\1\31\1\0\1\32"+
    "\2\0\1\33\1\34\1\35\1\0\1\36\1\37\1\40"+
    "\1\41\1\42\2\0\1\43\1\44\1\45\1\0\6\23"+
    "\1\46\3\23\1\47\3\23\1\50\2\23\1\51\4\23"+
    "\1\52\1\23\1\53\6\23\1\54\1\55\1\56\1\42"+
    "\1\0\1\57\11\23\1\60\17\23\1\61\4\23\1\62"+
    "\3\23\1\63\1\23\1\42\1\0\1\57\5\23\1\64"+
    "\12\23\1\65\4\23\1\66\7\23\1\67\2\23\1\70"+
    "\1\23\1\42\1\57\10\23\1\71\3\23\1\72\1\73"+
    "\5\23\1\74\1\75\4\23\1\76\3\23\1\42\3\23"+
    "\1\77\4\23\1\100\7\23\1\101\4\23\1\102\1\23"+
    "\1\103\1\23\1\104\2\23\1\105\1\23\1\106\1\23"+
    "\1\107\1\23\1\110\1\23\1\111\2\23\1\112\3\23"+
    "\1\113\2\23\1\114\1\115\1\116\5\23\1\117\1\23"+
    "\1\120\1\23\1\121\1\122\1\23\1\123\1\124";

  private static int [] zzUnpackAction() {
    int [] result = new int[273];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\107\0\107\0\107\0\216\0\325\0\107"+
    "\0\u011c\0\u0163\0\107\0\107\0\107\0\u01aa\0\107\0\u01f1"+
    "\0\u0238\0\107\0\u027f\0\u02c6\0\107\0\u030d\0\u0354\0\u039b"+
    "\0\u03e2\0\u0429\0\u0470\0\u04b7\0\u04fe\0\u0545\0\u058c\0\u05d3"+
    "\0\u061a\0\u0661\0\u06a8\0\u06ef\0\u0736\0\u077d\0\u07c4\0\u080b"+
    "\0\u0852\0\u0899\0\107\0\107\0\107\0\107\0\u08e0\0\107"+
    "\0\107\0\u0927\0\107\0\u096e\0\325\0\107\0\107\0\107"+
    "\0\u0163\0\107\0\107\0\107\0\107\0\u09b5\0\u0238\0\u09fc"+
    "\0\107\0\107\0\107\0\u0a43\0\u0a8a\0\u0ad1\0\u0b18\0\u0b5f"+
    "\0\u0ba6\0\u0bed\0\u0c34\0\u0c7b\0\u0cc2\0\u0d09\0\u0d50\0\u0d97"+
    "\0\u0dde\0\u0e25\0\u058c\0\u0e6c\0\u0eb3\0\u0efa\0\u0f41\0\u0f88"+
    "\0\u0fcf\0\u1016\0\u105d\0\u10a4\0\u10eb\0\u1132\0\u1179\0\u11c0"+
    "\0\u1207\0\u124e\0\u1295\0\107\0\107\0\107\0\u12dc\0\u1323"+
    "\0\u0a43\0\u136a\0\u13b1\0\u13f8\0\u143f\0\u1486\0\u14cd\0\u1514"+
    "\0\u155b\0\u15a2\0\107\0\u15e9\0\u1630\0\u1677\0\u16be\0\u1705"+
    "\0\u174c\0\u1793\0\u17da\0\u1821\0\u1868\0\u18af\0\u18f6\0\u193d"+
    "\0\u1984\0\u19cb\0\107\0\u1a12\0\u1a59\0\u1aa0\0\u1ae7\0\u058c"+
    "\0\u1b2e\0\u1b75\0\u1bbc\0\u058c\0\u1c03\0\u1c4a\0\u1c91\0\107"+
    "\0\u1cd8\0\u1d1f\0\u1d66\0\u1dad\0\u1df4\0\u058c\0\u1e3b\0\u1e82"+
    "\0\u1ec9\0\u1f10\0\u1f57\0\u1f9e\0\u1fe5\0\u202c\0\u2073\0\u20ba"+
    "\0\u058c\0\u2101\0\u2148\0\u218f\0\u21d6\0\u058c\0\u221d\0\u2264"+
    "\0\u22ab\0\u22f2\0\u2339\0\u2380\0\u23c7\0\u058c\0\u240e\0\u2455"+
    "\0\u058c\0\u249c\0\u24e3\0\u09fc\0\u252a\0\u2571\0\u25b8\0\u25ff"+
    "\0\u2646\0\u268d\0\u26d4\0\u271b\0\u058c\0\u2762\0\u27a9\0\u27f0"+
    "\0\u058c\0\u058c\0\u2837\0\u287e\0\u28c5\0\u290c\0\u2953\0\u058c"+
    "\0\u058c\0\u299a\0\u29e1\0\u2a28\0\u2a6f\0\u058c\0\u2ab6\0\u2afd"+
    "\0\u2b44\0\107\0\u2b8b\0\u2bd2\0\u2c19\0\u058c\0\u2c60\0\u2ca7"+
    "\0\u2cee\0\u2d35\0\u058c\0\u2d7c\0\u2dc3\0\u2e0a\0\u2e51\0\u2e98"+
    "\0\u2edf\0\u2f26\0\u058c\0\u2f6d\0\u2fb4\0\u2ffb\0\u3042\0\u058c"+
    "\0\u3089\0\u058c\0\u30d0\0\u058c\0\u3117\0\u315e\0\u058c\0\u31a5"+
    "\0\u058c\0\u31ec\0\u058c\0\u3233\0\u058c\0\u327a\0\u058c\0\u32c1"+
    "\0\u3308\0\u058c\0\u334f\0\u3396\0\u33dd\0\u058c\0\u3424\0\u346b"+
    "\0\u058c\0\u058c\0\u058c\0\u34b2\0\u34f9\0\u3540\0\u3587\0\u35ce"+
    "\0\u058c\0\u3615\0\u058c\0\u365c\0\u058c\0\u058c\0\u36a3\0\u058c"+
    "\0\u058c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[273];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\2\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\37"+
    "\1\43\1\44\1\37\1\45\1\46\1\47\1\50\1\51"+
    "\4\37\1\56\1\57\1\60\113\0\1\61\3\0\1\62"+
    "\15\0\1\63\56\0\1\64\1\0\5\65\1\66\101\65"+
    "\4\0\1\67\3\0\1\70\76\0\11\71\1\72\75\71"+
    "\15\0\1\73\10\0\1\74\77\0\1\75\111\0\2\76"+
    "\103\0\1\77\106\0\1\77\1\0\2\24\102\0\1\100"+
    "\6\0\1\101\106\0\1\102\106\0\1\103\1\104\101\0"+
    "\2\37\4\0\22\37\3\0\20\37\1\105\1\106\5\37"+
    "\25\0\2\37\4\0\22\37\3\0\16\37\1\107\10\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\110\14\37"+
    "\1\111\10\37\25\0\2\37\4\0\22\37\3\0\5\37"+
    "\1\112\10\37\1\113\10\37\25\0\2\37\4\0\22\37"+
    "\3\0\15\37\1\114\3\37\1\115\3\37\1\116\1\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\117\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\27\37\25\0\2\37"+
    "\4\0\22\37\3\0\1\37\1\120\25\37\25\0\2\37"+
    "\4\0\22\37\3\0\14\37\1\121\12\37\25\0\2\37"+
    "\4\0\22\37\3\0\5\37\1\122\21\37\25\0\2\37"+
    "\4\0\22\37\3\0\1\37\1\123\14\37\1\124\10\37"+
    "\25\0\2\37\4\0\22\37\3\0\5\37\1\125\3\37"+
    "\1\126\15\37\25\0\2\37\4\0\22\37\3\0\20\37"+
    "\1\127\6\37\25\0\2\37\4\0\22\37\3\0\1\37"+
    "\1\130\7\37\1\131\6\37\1\132\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\5\37\1\133\21\37\25\0\2\37"+
    "\4\0\22\37\3\0\1\37\1\134\7\37\1\135\4\37"+
    "\1\136\4\37\1\137\1\140\2\37\25\0\2\37\4\0"+
    "\22\37\3\0\20\37\1\141\6\37\25\0\2\37\4\0"+
    "\22\37\3\0\1\37\1\142\3\37\1\143\21\37\110\0"+
    "\1\144\11\0\1\145\203\0\1\146\23\0\2\147\63\0"+
    "\17\100\1\150\67\100\3\151\1\0\103\151\22\0\2\37"+
    "\4\0\22\37\3\0\20\37\1\152\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\3\37\1\153\23\37\25\0\2\37"+
    "\4\0\22\37\3\0\16\37\1\154\10\37\25\0\2\37"+
    "\4\0\22\37\3\0\4\37\1\155\13\37\1\156\1\157"+
    "\5\37\25\0\2\37\4\0\22\37\3\0\15\37\1\160"+
    "\11\37\25\0\2\37\4\0\22\37\3\0\6\37\1\161"+
    "\12\37\1\162\5\37\11\0\1\163\13\0\2\37\4\0"+
    "\22\37\3\0\2\37\1\164\24\37\25\0\2\37\4\0"+
    "\22\37\3\0\22\37\1\165\4\37\25\0\2\37\4\0"+
    "\22\37\3\0\17\37\1\166\7\37\25\0\2\37\4\0"+
    "\22\37\3\0\22\37\1\167\4\37\25\0\2\37\4\0"+
    "\22\37\3\0\13\37\1\170\13\37\25\0\2\37\4\0"+
    "\22\37\3\0\3\37\1\171\23\37\25\0\2\37\4\0"+
    "\22\37\3\0\17\37\1\172\7\37\25\0\2\37\4\0"+
    "\22\37\3\0\5\37\1\173\21\37\25\0\2\37\4\0"+
    "\22\37\3\0\15\37\1\174\11\37\25\0\2\37\4\0"+
    "\22\37\3\0\15\37\1\175\11\37\25\0\2\37\4\0"+
    "\22\37\3\0\5\37\1\176\21\37\25\0\2\37\4\0"+
    "\22\37\3\0\4\37\1\177\22\37\25\0\2\37\4\0"+
    "\22\37\3\0\20\37\1\200\6\37\25\0\2\37\4\0"+
    "\22\37\3\0\21\37\1\201\5\37\25\0\2\37\4\0"+
    "\22\37\3\0\11\37\1\202\15\37\11\0\1\203\13\0"+
    "\2\37\4\0\22\37\3\0\17\37\1\204\2\37\1\205"+
    "\4\37\25\0\2\37\4\0\22\37\3\0\13\37\1\206"+
    "\13\37\25\0\2\37\4\0\22\37\3\0\15\37\1\207"+
    "\11\37\25\0\2\37\4\0\22\37\3\0\13\37\1\210"+
    "\13\37\25\0\2\37\4\0\22\37\3\0\14\37\1\211"+
    "\12\37\25\0\2\37\4\0\22\37\3\0\11\37\1\212"+
    "\15\37\25\0\2\37\4\0\22\37\3\0\23\37\1\213"+
    "\3\37\25\0\2\37\4\0\22\37\3\0\20\37\1\214"+
    "\6\37\25\0\2\37\4\0\22\37\3\0\20\37\1\215"+
    "\6\37\25\0\2\216\63\0\17\100\1\217\7\100\1\220"+
    "\57\100\22\0\2\37\4\0\22\37\3\0\5\37\1\221"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\5\37\1\222"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\13\37\1\223"+
    "\13\37\25\0\2\37\4\0\22\37\3\0\5\37\1\224"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\1\37\1\225"+
    "\25\37\25\0\2\37\4\0\22\37\3\0\16\37\1\226"+
    "\10\37\25\0\2\37\4\0\22\37\3\0\22\37\1\227"+
    "\4\37\25\0\2\37\4\0\22\37\3\0\1\37\1\230"+
    "\25\37\25\0\2\37\4\0\22\37\3\0\3\37\1\231"+
    "\23\37\25\0\2\37\4\0\22\37\3\0\13\37\1\232"+
    "\13\37\25\0\2\37\4\0\22\37\3\0\5\37\1\233"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\5\37\1\234"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\11\37\1\235"+
    "\15\37\25\0\2\37\4\0\22\37\3\0\21\37\1\236"+
    "\5\37\25\0\2\37\4\0\22\37\3\0\5\37\1\237"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\1\37\1\240"+
    "\25\37\25\0\2\37\4\0\22\37\3\0\17\37\1\241"+
    "\7\37\25\0\2\37\4\0\22\37\3\0\7\37\1\242"+
    "\17\37\25\0\2\37\4\0\22\37\3\0\21\37\1\243"+
    "\5\37\25\0\2\37\4\0\22\37\3\0\15\37\1\244"+
    "\11\37\25\0\2\37\4\0\22\37\3\0\5\37\1\245"+
    "\21\37\25\0\2\37\4\0\22\37\3\0\1\37\1\246"+
    "\3\37\1\247\21\37\25\0\2\37\4\0\22\37\3\0"+
    "\22\37\1\250\4\37\25\0\2\37\4\0\22\37\3\0"+
    "\14\37\1\251\1\252\11\37\25\0\2\37\4\0\22\37"+
    "\3\0\20\37\1\253\6\37\25\0\2\37\4\0\22\37"+
    "\3\0\16\37\1\254\10\37\25\0\2\37\4\0\22\37"+
    "\3\0\11\37\1\255\15\37\25\0\2\37\4\0\22\37"+
    "\3\0\16\37\1\256\10\37\25\0\2\37\4\0\22\37"+
    "\3\0\1\37\1\257\25\37\25\0\2\37\4\0\22\37"+
    "\3\0\22\37\1\260\4\37\25\0\2\37\4\0\22\37"+
    "\3\0\5\37\1\261\21\37\25\0\2\37\4\0\22\37"+
    "\3\0\4\37\1\262\22\37\25\0\2\263\63\0\17\100"+
    "\1\150\7\100\1\264\57\100\22\0\2\37\4\0\22\37"+
    "\3\0\7\37\1\265\17\37\25\0\2\37\4\0\22\37"+
    "\3\0\15\37\1\266\11\37\25\0\2\37\4\0\22\37"+
    "\3\0\5\37\1\267\21\37\25\0\2\37\4\0\22\37"+
    "\3\0\15\37\1\270\11\37\25\0\2\37\4\0\22\37"+
    "\3\0\3\37\1\271\23\37\25\0\2\37\4\0\22\37"+
    "\3\0\11\37\1\272\15\37\25\0\2\37\4\0\22\37"+
    "\3\0\23\37\1\273\3\37\25\0\2\37\4\0\22\37"+
    "\3\0\5\37\1\274\21\37\25\0\2\37\4\0\22\37"+
    "\3\0\5\37\1\275\21\37\25\0\2\37\4\0\22\37"+
    "\3\0\20\37\1\276\6\37\25\0\2\37\4\0\22\37"+
    "\3\0\20\37\1\277\6\37\25\0\2\37\4\0\22\37"+
    "\3\0\5\37\1\300\21\37\25\0\2\37\4\0\22\37"+
    "\3\0\5\37\1\301\10\37\1\301\10\37\25\0\2\37"+
    "\4\0\22\37\3\0\20\37\1\302\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\20\37\1\303\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\11\37\1\304\15\37\25\0\2\37"+
    "\4\0\22\37\3\0\1\37\1\305\25\37\25\0\2\37"+
    "\4\0\22\37\3\0\22\37\1\306\4\37\25\0\2\37"+
    "\4\0\22\37\3\0\15\37\1\307\11\37\25\0\2\37"+
    "\4\0\22\37\3\0\21\37\1\310\5\37\25\0\2\37"+
    "\4\0\22\37\3\0\1\37\1\311\25\37\25\0\2\37"+
    "\4\0\22\37\3\0\16\37\1\312\10\37\25\0\2\37"+
    "\4\0\22\37\3\0\3\37\1\313\23\37\25\0\2\37"+
    "\4\0\22\37\3\0\16\37\1\314\10\37\25\0\2\37"+
    "\4\0\22\37\3\0\20\37\1\315\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\20\37\1\316\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\20\37\1\317\6\37\25\0\2\37"+
    "\4\0\22\37\3\0\3\37\1\320\23\37\25\0\2\37"+
    "\4\0\22\37\3\0\1\37\1\321\25\37\25\0\2\322"+
    "\105\0\2\37\4\0\22\37\3\0\13\37\1\323\13\37"+
    "\25\0\2\37\4\0\22\37\3\0\4\37\1\324\22\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\325\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\326\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\22\37\1\327\4\37"+
    "\25\0\2\37\4\0\22\37\3\0\15\37\1\330\11\37"+
    "\25\0\2\37\4\0\22\37\3\0\13\37\1\331\13\37"+
    "\25\0\2\37\4\0\22\37\3\0\15\37\1\332\11\37"+
    "\25\0\2\37\4\0\22\37\3\0\16\37\1\333\10\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\334\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\15\37\1\335\11\37"+
    "\25\0\2\37\4\0\22\37\3\0\5\37\1\336\21\37"+
    "\25\0\2\37\4\0\22\37\3\0\22\37\1\337\4\37"+
    "\25\0\2\37\4\0\22\37\3\0\12\37\1\340\14\37"+
    "\25\0\2\37\4\0\22\37\3\0\20\37\1\341\6\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\342\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\21\37\1\343\5\37"+
    "\25\0\2\37\4\0\22\37\3\0\11\37\1\344\15\37"+
    "\25\0\2\37\4\0\22\37\3\0\4\37\1\345\22\37"+
    "\25\0\2\37\4\0\22\37\3\0\15\37\1\346\11\37"+
    "\25\0\2\37\4\0\22\37\3\0\11\37\1\347\15\37"+
    "\25\0\2\37\4\0\22\37\3\0\10\37\1\350\16\37"+
    "\25\0\2\37\4\0\22\37\3\0\4\37\1\351\22\37"+
    "\25\0\2\37\4\0\22\37\3\0\16\37\1\352\10\37"+
    "\25\0\2\37\4\0\22\37\3\0\5\37\1\353\21\37"+
    "\25\0\2\37\4\0\22\37\3\0\15\37\1\354\11\37"+
    "\25\0\2\37\4\0\22\37\3\0\5\37\1\355\21\37"+
    "\25\0\2\37\4\0\22\37\3\0\23\37\1\356\3\37"+
    "\25\0\2\37\4\0\22\37\3\0\22\37\1\357\4\37"+
    "\25\0\2\37\4\0\22\37\3\0\4\37\1\360\22\37"+
    "\25\0\2\37\4\0\22\37\3\0\20\37\1\361\6\37"+
    "\25\0\2\37\4\0\22\37\3\0\4\37\1\362\22\37"+
    "\25\0\2\37\4\0\22\37\3\0\21\37\1\363\5\37"+
    "\25\0\2\37\4\0\22\37\3\0\23\37\1\364\3\37"+
    "\25\0\2\37\4\0\22\37\3\0\5\37\1\365\21\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\366\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\20\37\1\367\6\37"+
    "\25\0\2\37\4\0\22\37\3\0\17\37\1\370\7\37"+
    "\25\0\2\37\4\0\22\37\3\0\23\37\1\371\3\37"+
    "\25\0\2\37\4\0\22\37\3\0\1\37\1\372\25\37"+
    "\25\0\2\37\4\0\22\37\3\0\26\37\1\373\25\0"+
    "\2\37\4\0\22\37\3\0\5\37\1\374\21\37\25\0"+
    "\2\37\4\0\22\37\3\0\15\37\1\375\11\37\25\0"+
    "\2\37\4\0\22\37\3\0\20\37\1\376\6\37\25\0"+
    "\2\37\4\0\22\37\3\0\1\37\1\377\25\37\25\0"+
    "\2\37\4\0\22\37\3\0\5\37\1\u0100\21\37\25\0"+
    "\2\37\4\0\22\37\3\0\5\37\1\u0101\21\37\25\0"+
    "\2\37\4\0\22\37\3\0\4\37\1\u0102\22\37\25\0"+
    "\2\37\4\0\22\37\3\0\21\37\1\u0103\5\37\25\0"+
    "\2\37\4\0\22\37\3\0\1\37\1\u0104\25\37\25\0"+
    "\2\37\4\0\22\37\3\0\3\37\1\u0105\23\37\25\0"+
    "\2\37\4\0\22\37\3\0\1\37\1\u0106\25\37\25\0"+
    "\2\37\4\0\22\37\3\0\20\37\1\u0107\6\37\25\0"+
    "\2\37\4\0\22\37\3\0\22\37\1\u0108\4\37\25\0"+
    "\2\37\4\0\22\37\3\0\20\37\1\u0109\6\37\25\0"+
    "\2\37\4\0\22\37\3\0\15\37\1\u010a\11\37\25\0"+
    "\2\37\4\0\22\37\3\0\13\37\1\u010b\13\37\25\0"+
    "\2\37\4\0\22\37\3\0\11\37\1\u010c\15\37\25\0"+
    "\2\37\4\0\22\37\3\0\20\37\1\u010d\6\37\25\0"+
    "\2\37\4\0\22\37\3\0\16\37\1\261\10\37\25\0"+
    "\2\37\4\0\22\37\3\0\5\37\1\u010e\21\37\25\0"+
    "\2\37\4\0\22\37\3\0\22\37\1\u010f\4\37\25\0"+
    "\2\37\4\0\22\37\3\0\20\37\1\u0110\6\37\25\0"+
    "\2\37\4\0\22\37\3\0\5\37\1\u0111\21\37\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14058];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\11\2\1\1\11\2\1\3\11\1\1\1\11"+
    "\2\1\1\11\2\1\1\11\25\1\4\11\1\1\2\11"+
    "\1\0\1\11\2\0\3\11\1\0\4\11\1\1\2\0"+
    "\3\11\1\0\37\1\3\11\1\1\1\0\12\1\1\11"+
    "\17\1\1\11\13\1\1\0\1\11\101\1\1\11\77\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[273];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    ArrayList<LexicalError> list = new ArrayList();
    LexicalError error;

    public ArrayList<LexicalError> getList(){
        return list;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PhytonLexic(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { if(error==null){
        error = new LexicalError(yyline+1, yycolumn+1);
        error.setDescription("Lexema no reconocido");
    }
    error.setLexema(yytext());
            }
            // fall through
          case 85: break;
          case 2:
            { if(error!=null){list.add(error); error=null;}
            }
            // fall through
          case 86: break;
          case 3:
            { System.out.println("TAB"); 
            if(error!=null){list.add(error); error=null;}
            return new Symbol(TAB, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 87: break;
          case 4:
            { System.out.println("SALTO");
        if(error!=null){list.add(error); error=null;}
        return new Symbol(SPACE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 88: break;
          case 5:
            { System.out.println(yytext());if(error==null){ return new Symbol(NOT, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 89: break;
          case 6:
            { System.out.println(yytext());if(error==null){ return new Symbol(MODULE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 90: break;
          case 7:
            { System.out.println(yytext());if(error==null){ return new Symbol(OPEN_PARENTHESIS, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 91: break;
          case 8:
            { System.out.println(yytext());if(error==null){ return new Symbol(CLOSE_PARENTHESIS, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 92: break;
          case 9:
            { System.out.println(yytext());if(error==null){ return new Symbol(MULTIPLY, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 93: break;
          case 10:
            { System.out.println(yytext());if(error==null){ return new Symbol(ADD, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 94: break;
          case 11:
            { System.out.println(yytext());if(error==null){ return new Symbol(COMA, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 95: break;
          case 12:
            { System.out.println(yytext());if(error==null){ return new Symbol(MINUS, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 96: break;
          case 13:
            { System.out.println(yytext());if(error==null){ return new Symbol(DIV, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 97: break;
          case 14:
            { System.out.println("NUMERO "+yytext());if(error==null){ return new Symbol(NUMBER, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 98: break;
          case 15:
            { System.out.println(yytext());if(error==null){ return new Symbol(COLON, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 99: break;
          case 16:
            { System.out.println(yytext());if(error==null){ return new Symbol(LESSER, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 100: break;
          case 17:
            { System.out.println(yytext());if(error==null){ return new Symbol(EQUAL, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 101: break;
          case 18:
            { System.out.println(yytext());if(error==null){ return new Symbol(GREATER, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 102: break;
          case 19:
            { System.out.println("SIMBOLO "+yytext());
        if(error==null){ 
            return new Symbol(SIMBOLO, yyline+1, yycolumn+1, yytext());
        }else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 103: break;
          case 20:
            { System.out.println(yytext());
            if(error==null){ 
                return new Symbol(OPEN_BRACKET, yyline+1, yycolumn+1, yytext());
            }else{
                error.setLexema(yytext());
            }
            }
            // fall through
          case 104: break;
          case 21:
            { System.out.println(yytext());if(error==null){ return new Symbol (CLOSE_BRACKET, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 105: break;
          case 22:
            { System.out.println(yytext());if(error==null){ return new Symbol(POW, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 106: break;
          case 23:
            { System.out.println(yytext());if(error==null){ return new Symbol (OPEN_CURLY, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 107: break;
          case 24:
            { System.out.println(yytext());if(error==null){ return new Symbol (CLOSE_CURLY, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 108: break;
          case 25:
            { System.out.println(yytext());if(error==null){ return new Symbol(NULL_, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 109: break;
          case 26:
            { System.out.println(yytext());if(error==null){ return new Symbol(DIFFERENTIATION, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 110: break;
          case 27:
            { System.out.println(yytext());if(error==null){ return new Symbol(STRING, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 111: break;
          case 28:
            { System.out.println(yytext());if(error==null){ return new Symbol(XOR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 112: break;
          case 29:
            { System.out.println(yytext());if(error==null){ return new Symbol(AND, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 113: break;
          case 30:
            { System.out.println(yytext());if(error==null){ return new Symbol(CHAR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 114: break;
          case 31:
            { System.out.println(yytext());if(error==null){ return new Symbol(INCREASE, yyline+1,yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 115: break;
          case 32:
            { System.out.println(yytext());if(error==null){ return new Symbol(EQUAL_MORE,yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 116: break;
          case 33:
            { System.out.println(yytext());if(error==null){ return new Symbol(DECREASE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 117: break;
          case 34:
            { System.out.println("DECIMAL "+yytext());if(error==null){ return new Symbol(DECIMAL, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 118: break;
          case 35:
            { System.out.println(yytext());if(error==null){ return new Symbol(LESSER_THAN, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 119: break;
          case 36:
            { System.out.println(yytext());if(error==null){ return new Symbol(EQUALIZATION, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 120: break;
          case 37:
            { System.out.println(yytext());if(error==null){ return new Symbol(GREATER_THAN, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 121: break;
          case 38:
            { System.out.println(yytext());if(error==null){ return new Symbol(DO, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 122: break;
          case 39:
            { System.out.println(yytext());if(error==null){ return new Symbol(FA, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 123: break;
          case 40:
            { System.out.println(yytext());if(error==null){ return new Symbol(LA, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 124: break;
          case 41:
            { System.out.println(yytext());if(error==null){ return new Symbol(MI, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 125: break;
          case 42:
            { System.out.println(yytext());if(error==null){ return new Symbol(RE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 126: break;
          case 43:
            { System.out.println(yytext());if(error==null){ return new Symbol(SI, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 127: break;
          case 44:
            { System.out.println(yytext());if(error==null){ return new Symbol(OR, yyline+1, yycolumn+1,yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 128: break;
          case 45:
            { System.out.println(yytext());if(error==null){ return new Symbol(NAND, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 129: break;
          case 46:
            { System.out.println(yytext());if(error==null){ return new Symbol(NOR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 130: break;
          case 47:
            { /*empty*/
            }
            // fall through
          case 131: break;
          case 48:
            { System.out.println(yytext());if(error==null){ return new Symbol(DOR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 132: break;
          case 49:
            { System.out.println(yytext());if(error==null){ return new Symbol(RER, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 133: break;
          case 50:
            { System.out.println(yytext());if(error==null){ return new Symbol(SOL, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 134: break;
          case 51:
            { System.out.println(yytext());if(error==null){ return new Symbol(VAR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 135: break;
          case 52:
            { System.out.println(yytext());if(error==null){ return new Symbol(CASE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 136: break;
          case 53:
            { System.out.println(yytext());if(error==null){ return new Symbol(KEEP, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 137: break;
          case 54:
            { System.out.println(yytext());if(error==null){ return new Symbol(FOR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 138: break;
          case 55:
            { System.out.println(yytext());
                if(error==null){
                    return new Symbol(ELSE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 139: break;
          case 56:
            { System.out.println(yytext());if(error==null){ return new Symbol(TRUE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 140: break;
          case 57:
            { System.out.println(yytext());if(error==null){ return new Symbol(DOBLE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 141: break;
          case 58:
            { System.out.println(yytext());if(error==null){ return new Symbol(FALSE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 142: break;
          case 59:
            { System.out.println(yytext());if(error==null){ return new Symbol(HACER, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 143: break;
          case 60:
            { System.out.println(yytext());if(error==null){ return new Symbol(PARES, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 144: break;
          case 61:
            { System.out.println(yytext());if(error==null){ return new Symbol(PISTA, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 145: break;
          case 62:
            { System.out.println(yytext());if(error==null){ return new Symbol(EXIT, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 146: break;
          case 63:
            { System.out.println(yytext());if(error==null){ return new Symbol(CADENA, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 147: break;
          case 64:
            { System.out.println(yytext());if(error==null){ return new Symbol(ENTERO, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 148: break;
          case 65:
            { System.out.println(yytext());if(error==null){ return new Symbol(PRIMOS, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 149: break;
          case 66:
            { System.out.println(yytext());
        if(error==null){
            return new Symbol(SWITCH, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 150: break;
          case 67:
            { System.out.println(yytext());if(error==null){ return new Symbol(ARREGLO, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 151: break;
          case 68:
            { System.out.println(yytext());if(error==null){ return new Symbol(BOOLEAN, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 152: break;
          case 69:
            { System.out.println(yytext());if(error==null){ return new Symbol(DEFAULT, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 153: break;
          case 70:
            { System.out.println(yytext());if(error==null){ return new Symbol(ESPERAR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 154: break;
          case 71:
            { System.out.println(yytext());if(error==null){ return new Symbol(IMPARES, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 155: break;
          case 72:
            { System.out.println(yytext());if(error==null){ return new Symbol(MENSAJE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 156: break;
          case 73:
            { System.out.println(yytext());if(error==null){ return new Symbol(ORDENAR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 157: break;
          case 74:
            { System.out.println(yytext());if(error==null){ return new Symbol(RETORNA, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 158: break;
          case 75:
            { System.out.println(yytext());if(error==null){ return new Symbol(CARACTER, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 159: break;
          case 76:
            { System.out.println(yytext());if(error==null){ return new Symbol(EXTIENDE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 160: break;
          case 77:
            { System.out.println(yytext());if(error==null){ return new Symbol(LONGITUD, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 161: break;
          case 78:
            { System.out.println(yytext());if(error==null){ return new Symbol(WHILE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 162: break;
          case 79:
            { System.out.println(yytext());if(error==null){ return new Symbol(CONTINUE,yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 163: break;
          case 80:
            { System.out.println(yytext());if(error==null){ return new Symbol(PRINCIPAL, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 164: break;
          case 81:
            { System.out.println(yytext());if(error==null){ return new Symbol(SUMARIZAR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 165: break;
          case 82:
            { System.out.println(yytext());if(error==null){ return new Symbol(ASCENDENTE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 166: break;
          case 83:
            { System.out.println(yytext());if(error==null){ return new Symbol(REPRODUCIR, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 167: break;
          case 84:
            { System.out.println(yytext());if(error==null){ return new Symbol(DESCENDENTE, yyline+1, yycolumn+1, yytext());}else{
            error.setLexema(yytext());
        }
            }
            // fall through
          case 168: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
