
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package valiente.orl2.Lista.parser;

/** CUP generated class containing symbol constants. */
public class PlaySym {
  /* terminals */
  public static final int CLOSE_BRACKET = 12;
  public static final int PIPE = 13;
  public static final int OPEN_CURLY = 14;
  public static final int TRUE = 7;
  public static final int SEMI_COLON = 16;
  public static final int PISTA = 6;
  public static final int OPEN_BRACKET = 11;
  public static final int COMA = 17;
  public static final int STRING = 9;
  public static final int RANDOM = 4;
  public static final int NOMBRE = 3;
  public static final int EOF = 0;
  public static final int CIRCULAR = 5;
  public static final int SIMBOLO = 10;
  public static final int FALSE = 8;
  public static final int error = 1;
  public static final int CLOSE_CURLY = 15;
  public static final int LISTA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LISTA",
  "NOMBRE",
  "RANDOM",
  "CIRCULAR",
  "PISTA",
  "TRUE",
  "FALSE",
  "STRING",
  "SIMBOLO",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "PIPE",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "SEMI_COLON",
  "COMA"
  };
}

