
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package valiente.orl2.communication;

/** CUP generated class containing symbol constants. */
public class CommunicationSym {
  /* terminals */
  public static final int DURACION = 12;
  public static final int EQUAL = 22;
  public static final int DECIMAL = 3;
  public static final int OCTAVA = 18;
  public static final int DATOS = 17;
  public static final int GREATER = 20;
  public static final int PISTA = 26;
  public static final int LISTAS = 8;
  public static final int NOTE = 24;
  public static final int TIPO = 6;
  public static final int STRING = 2;
  public static final int NOTA = 15;
  public static final int NOMBRE = 7;
  public static final int EOF = 0;
  public static final int NUMBER = 4;
  public static final int CIRCULAR = 25;
  public static final int DIV = 21;
  public static final int SIMBOLO = 23;
  public static final int CANAL = 13;
  public static final int error = 1;
  public static final int NUMERO = 14;
  public static final int FRECUENCIA = 16;
  public static final int PISTAS = 10;
  public static final int LISTA = 9;
  public static final int SOLICITUD = 5;
  public static final int ALEATORIA = 11;
  public static final int LESS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "DECIMAL",
  "NUMBER",
  "SOLICITUD",
  "TIPO",
  "NOMBRE",
  "LISTAS",
  "LISTA",
  "PISTAS",
  "ALEATORIA",
  "DURACION",
  "CANAL",
  "NUMERO",
  "NOTA",
  "FRECUENCIA",
  "DATOS",
  "OCTAVA",
  "LESS",
  "GREATER",
  "DIV",
  "EQUAL",
  "SIMBOLO",
  "NOTE",
  "CIRCULAR",
  "PISTA"
  };
}

